# fly.toml app configuration file generated for carrito-compras on 2024-04-24T10:57:38-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'carrito-compras'
primary_region = 'eze'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
